// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5026' | (string & {});
};

export type LoginRequestDto = {
    usernameOrEmail: string;
    password: string;
};

export type RegisterRequestDto = {
    username: string;
    email: string;
    password: string;
    confirmPassword: string;
    fullName: string;
    phoneNumber?: string | null;
    identityCard?: string | null;
};

export type PostApiAuthLoginData = {
    body?: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthRegisterData = {
    body?: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTestUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test_users';
};

export type GetApiTestUsersResponses = {
    /**
     * OK
     */
    200: unknown;
};
